config/routes.rb
ActionController::Routing::Routes.draw do |map|

  map.resources :s3_uploads, :collection=>{:save_to_database=>[:post]}

  map.resources :formats

  map.resources :prices

  map.resources :options

  map.resources :printtypes

  map.resources :papers

  map.resources :updates

  map.new_order "orders/new/:printtype", :controller=>:orders,:action=>:new
  map.contact "kontakt", :controller=>:home,:action=>:contact

 map.resources :orders, :collection=>{:new_image=>[:post,:put]}, :member=>{:step_two=>[:get,:put]}

  map.devise_for :users, :as=>"uzytkownik"
  map.resources :users, :member=>{:change_password=>[:get, :put]}

  

  map.root :controller=> :home
  map.connect ':controller/:action/:id'
  map.connect ':controller/:action/:id.:format'
end

   ActionController::Routing::Translator.i18n('pl')

app/models/option.rb
class Option < ActiveRecord::Base
  has_and_belongs_to_many :printtypes
  has_and_belongs_to_many :orders
  named_scope :per_unit, :conditions=>{:per_unit=>true}
  named_scope :not_per_unit, :conditions=>{:per_unit=>false}
end

app/controllers/options_controller.rb
class OptionsController < ApplicationController
  before_filter :verify_admin
  
  def index
    @options = Option.all
  end
  
  def show
    @option = Option.find(params[:id])
  end
  
  def new
    @option = Option.new
    @option.printtypes.build
  end
  
  def create
    @option = Option.new(params[:option])
    if @option.save
      flash[:notice] = "Obiekt został pomyślnie dodany."
      redirect_to @option
    else
      render :action => 'new'
    end
  end
  
  def edit
    @option = Option.find(params[:id])
  end
  
  def update
    @option = Option.find(params[:id])
    if @option.update_attributes(params[:option])
      flash[:notice] = "Pomyślnie zaktualizowano obiekt."
      redirect_to @option
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @option = Option.find(params[:id])
    @option.destroy
    flash[:notice] = "Pomyślnie usunięto obiekt."
    redirect_to options_url
  end
end

app/helpers/options_helper.rb
module OptionsHelper
end

app/views/options/_form.html.erb
<% form_for @option do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </p>
  <p>
    <%= f.label :per_unit %><br />
    <%= f.check_box :per_unit %>
  </p>
<p>
    <%= f.label :printtype_id %><br />
      </p>
    <ul>

    <% Printtype.all.each do |t|%>
    <li>
      <%= @option.printtypes.include?(t) %>
            <%= check_box_tag "option[printtype_ids][]", t.id%>
            <span><%= t.name%></span>
          </li>

          <% end%>
        </ul>
  <p><%= f.submit "Zapisz"%></p>
<% end %>

app/views/options/edit.html.erb
<% title "Edytuj Opcję" %>

<%= render :partial => 'form' %>

<p>
  <%= link_to "Pokaż", @option %> |
  <%= link_to "Pokaż wszystkie", options_path %>
</p>

app/views/options/index.html.erb
<% title "Opcje" %>

<table>
  <tr>
    <th>Nazwa</th>
    <th>Cena</th>
    <th>od ilości?</th>
    <th>Typ druku</th>
  </tr>
  <% for option in @options %>
    <tr>
      <td><%=h option.name %></td>
      <td><%=h option.price %></td>
      <td><%=h option.per_unit %></td>
      <td><%=h option.printtypes.collect{|p|p.name+" | "}%></td>
      <td><%= link_to "Pokaż", option %></td>
      <td><%= link_to "Edytuj", edit_option_path(option) %></td>
      <td><%= link_to "Usuń", option, :confirm => "Czy jesteś pewny?", :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "Nowa opcja", new_option_path %></p>

app/views/options/new.html.erb
<% title "Nowa opcja" %>

<%= render :partial => 'form' %>

<p><%= link_to "Powrót do listy", options_path %></p>

app/views/options/show.html.erb
<% title "Opcja" %>

<p>
  <strong>Name:</strong>
  <%=h @option.name %>
</p>
<p>
  <strong>Price:</strong>
  <%=h @option.price %>
</p>
<p>
  <strong>Per Unit:</strong>
  <%=h @option.per_unit %>
</p>
  <strong>Printtype:</strong>
  <ul>
  <% @option.printtypes.each do |p|%>
  <li><%= p.name%></li>
      <% end%>
</ul>

<p>
  <%= link_to "Edytuj", edit_option_path(@option) %> |
  <%= link_to "Usuń", @option, :confirm => "Czy jesteś pewny?", :method => :delete %> |
  <%= link_to "Pokaż wszystkie", options_path %>
</p>